language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=migrations
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"
install:
  - pip install -U tox-travis
script:
  - tox
